<?php echo $this->doctype() ?>
<html lang="en" data-ng-app="app">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Destiny Packmule</title>

    <link href="/application/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div id="wrapper">
    <div class="container"><?=$this->content;?></div>
</div>

</body>
</html>
